### ISSUE TITLE
OK to reproduce?

### ISSUE THREAD

**Issue by bryevdv** [zonination/perceptions#2]
Hi, you have some terrific visualizations. I'm one of the core devs for Bokeh:

http://bokeh.pydata.org/en/latest/index.html
https://github.com/bokeh/bokeh

I've been wanting to expand our examples with some more interesting visualizations base on real data. I'm a tinker and a toolmaker, but unlike you, *not* a great data hobbyist. Would you mind if I reproduced some of your fantastic visualizations with Bokeh, for the Bokeh documentation (with attribution pointing back to your GH)?

**Comment by zonination** [comment]
bryevdev,

Feel free to use this with the attribution you describe.

**Comment by bryevdv** [comment]
Thanks!

**Comment by Codename-Catbox** [comment]
Hi. I’m new here, just an independent student. May I make hard-copy for study?
