### ISSUE TITLE
Direct link to reddit source

### ISSUE THREAD

**Issue by lssimoes** [zonination/perceptions#4]
Hi,

I search r/samplesize with the query you mentioned but I could not find the relevant thread.. Would you mind sharing the direct link to the data source?

Thanks and those are really nice plots!

**Comment by zonination** [comment]
Here are multiple sources:

* The [reddit thread](https://www.reddit.com/r/SampleSize/comments/3h13c5/casual_perception_of_probability_and_numbers/) querying individual responses
* A link [to the survey](https://docs.google.com/forms/d/e/1FAIpQLSctLm6BS31a_YiDbYAIZR5ghmefx1qKiCkYCjyhzvUDjlajgw/viewform)
* The raw data files also present on my github: [probabilities](https://github.com/zonination/perceptions/blob/master/probly.csv), [numbers](https://github.com/zonination/perceptions/blob/master/numberly.csv)

Hope this helps. Best wishes.
